config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  root to: 'homes#top'
  devise_for :users
  resources :users, only: [:new, :create, :index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, :optional => true

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: {minimum: 2}
  validates :name, length: {maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end



  def after_update_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "creating successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      redirect_to user_path(user_id)
    end
  end

  def index
    @books = Book.all
    render 'books/show'
  end

  def show
    @book.user_id = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path
    else
      flash[:alert] = "Updating error."
      redirect_to book_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "creating successfully"
      redirect_to user_path(id:current_user)
    else
      @users = User.all
      render :index
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
    render 'books/show'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<%= render 'users/list' , users: @user %>
<table>
  <h1><b>Book detail</b></h1>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>Create Books</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title<h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'create book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @user, :profile_image , :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></br>
              <%= @user.name %>
            </td>
            <td><%= @book.user_id.title %></td>
            <td><%= @book.user_id.body %></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to Bookers</h1>
<h4>CopyRight Infratop.inc</h4>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
        </div>
        <p>
            In <i class="fas fa-book"></i><strong>Bookers</strong>,
        </p>
        <p>
            you can share and exchange your opinions ,inpressions ,and emotions </br>about various book!
        </p>
        <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
               <button class ="btn btn-primary btnblue" type = "button" >
                   <%= link_to "Log in", new_user_session_path, class:"link" %>
               </button>
            </div>
            <div class="row">
                <button class ="btn btn-primary btngreen" type = "button" >
                    <%= link_to "Sign up", new_user_registration_path, class:"link" %>
                </button>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark db-dark">
        <div class="container">
          <span class= "grey">
            <%= link_to "Bookers", root_path,class:"link" %>
          </span>
          <div class="collapse navbar-collapse" id="nabvarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Home",user_path(current_user.id), class:"link fas fa-home" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Users",users_path, class:"link fas fa-users" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Books", books_path, class:"link fas fa-book-open"  %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, class:"link fas fa-sign-out-alt" , method: :delete %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Home", root_path, class:"link fas fa-home" %>
                </li>
                <li class="nav-item">
                  <%= link_to "About", home_about_path, class:"link fas fa-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class:"link fas fa-user-plus" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log in", new_user_session_path, class:"link fas fa-sign-in-alt" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <h2 class="mt-3">User info</h2>
    <%= attachment_image_tag @user, :profile_image , :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <% if @user.id == current_user.id %>
        <p><%= link_to "Edit", edit_user_path(@user), class:"link btn btn-success" %></p>
      <% end %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class="form-gorup">
        <%= form_with model: @user, local:true do |user| %>
          <div class="form-group">
            <label>Name</label>
            <%= user.text_field :name %>
          </div>
          <div class="form-group">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <label>Image</label>
            <%= user.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form-group">
            <label>Introduction</label>
            <%= user.text_area :introduction %>
          </div>
          <div class="form-group btn">
            <%= user.submit 'Update User',class:"link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<table>
  <thead>
    <th><b>Title</b></th>
    <th><b>Option</b></th>
  </thead>

  <tbody>
    <%  @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><td>
      <td><%= user.name %></td>
      <td><%= user.introduction %></td>
   </tr>
   <% end %>
  </tbody>
</table>%

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></th>
            <% @books.each do |book|%>
            <th><%= book.title %></th>
            <th><%= book.body %></th>
            <% end%>
          </tr>
        </tbody>

      </table>
    </div>
  </div>
</div>